name: crm
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    user: root
    working_dir: /home/frappe
    command: bash /workspace/init-production.sh
    environment:
      - SHELL=/bin/bash
    volumes:
      - .:/workspace
    depends_on:
      - mariadb
      - redis
    deploy:
      resources:
        limits:
          memory: 4g

volumes:
  mariadb-data:
